name: elcontrasteappbeta
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  card_swiper: ^3.0.1
  flutter:
    sdk: flutter
  go_router: ^14.6.0
  http: ^0.13.3
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
